### PR TITLE
Addition of Segments in the Progress Bar

### PR DESCRIPTION
**Pull request by PenseeNumerique**
The color resources for ProgressColor and GradientColor have been reorganized in MainPage.xaml. Added a ScrollView to allow scrolling of the page content. Added a "Segment usage" section in MainPage.xaml to demonstrate the use of segments in the progress bar. Added new properties in ProgressBar.cs to manage segments: UseSegment, SegmentSpacing, SegmentCount, and ProgressSegment. Modified the DrawProgress method to include the logic for drawing segments if UseSegment is enabled. Added GenerateProgress and GenerateSegment methods to separate the drawing logic for progress and segments. The base color is now set as transparent when segments are used.

https://github.com/ewerspej/epj.ProgressBar.Maui/issues/6

### CODE REVIEW

**Comment by ewerspej** [comment]
Hi @PenseeNumerique! Thank you for your pull request. I already had a quick glance and overall, it looks good. However, there are a few things that need to be addressed. For example, I would like to keep the formatting consistent. For that, I will add my local style configuration files to the repo. Please use XamlStyler (for XAML) as well as the formatting capabilities of Visual Studio (for C#). When I find the time, I'll give more direct feedback after having downloaded and tested the code. This looks very promising and I'm happy to integrate this once it's ready.

**Comment by PenseeNumerique** [comment]
No problem, it's your project, I just wanted to propose a few things that I needed in my project:)

**Comment by ewerspej** [comment]
Hi @PenseeNumerique ,

I've added the editor config and XamlStyler rules. Please pull the changes, update your code, resolve any conflicts and apply the formatting. Afterwards, I'll review your PR and test the changes.

Cheers
Julian

**Comment by PenseeNumerique** [comment]
I'm sorry, but I don't see the changes. Maybe I don't know where to look.

**Comment by PenseeNumerique** [comment]
I'm sorry, but I don't see the changes. Maybe I don't know where to look. I look only conflit but it's ce same code :/

**Comment by ewerspej** [comment]
You'll need to pull the changes from my repository (main branch) and merge that into your fork, then you'll see the conflicts and afterwards, you can update your PR.

**Comment by ewerspej** [comment]
@PenseeNumerique I changed the PR into a draft. You can update it and reopen the PR anytime. I like and appreciate this addition to the control. If resolving the conflicts doesn't work, you can also save your changes, pull from the main branch again into your local fork and create a new PR, if that helps.

**Comment by PenseeNumerique** [comment]
Thank you, I'll check it out at the end of the week or next week. I have a lot of work at the moment ^^'

**Comment by ewerspej** [comment]
I'm looking forward to it! Have a nice week.

**Comment by ewerspej** [comment]
@PenseeNumerique Any update?

**Pull request closed without merging**
